[package]
name = "_486_demo"
version = "0.1.0"
authors = ["Florent Le Gall <florent.legall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"

[dependencies]
rlibc = "1.0.0"
